In [22]:
#Although this toolset was developed to simplify data management, it proved preferable to simply carry out processing 
#semi-manually in excel

import pandas as pd
import jellyfish as jf

def comPairison(ini, sec, th):
    #code updated from https://miguendes.me/python-compare-strings
    #For a given threshold of similarity in keystrokes, determines if two strings belong matched together.
    #provide ini and sec in the form of strings, th in the form of an integer.
    
    return jf.damerau_levenshtein_distance(ini,sec) <= th

def sexIngest(file, product):
    #takes a census data CSV with gender delineated data and outputs a version with only total values. Parameters as strings.
    f = pd.read_csv(file)
    for i in list(f):
        for u in list(f):
            if i != u:
            #for the purposes of gendered census data, the difference will be 3 between Male and Female.
                if comPairison(i,u,3) == True:
                    q = i + ('_combinedSexes')
                    f[q] = f[i] + f[u] 
    f.to_csv(product)
    return f

In [28]:
sexIngest('other_data/2014/Sex_By_Age/ACSDT5Y2014.B01001_data_with_overlays_2022-02-20T224514_test.csv', 'other_data/2014/Sex_By_Age/age_data.csv')

,Estimate!!Total,Margin of Error!!Total,Estimate!!Total!!Male,Margin of Error!!Total!!Male,Estimate!!Total!!Male!!Under 5 years,Margin of Error!!Total!!Male!!Under 5 years,Estimate!!Total!!Male!!5 to 9 years,Margin of Error!!Total!!Male!!5 to 9 years,Estimate!!Total!!Male!!10 to 14 years,Margin of Error!!Total!!Male!!10 to 14 years,...,Estimate!!Total!!Female!!67 to 69 years_combinedSexes,Margin of Error!!Total!!Female!!67 to 69 years_combinedSexes,Estimate!!Total!!Female!!70 to 74 years_combinedSexes,Margin of Error!!Total!!Female!!70 to 74 years_combinedSexes,Estimate!!Total!!Female!!75 to 79 years_combinedSexes,Margin of Error!!Total!!Female!!75 to 79 years_combinedSexes,Estimate!!Total!!Female!!80 to 84 years_combinedSexes,Margin of Error!!Total!!Female!!80 to 84 years_combinedSexes,Estimate!!Total!!Female!!85 years and over_combinedSexes,Margin of Error!!Total!!Female!!85 years and over_combinedSexes
0,665,98,360,70,0,12,19,6,23,18,...,35,31,14,16,20,17,14,16,9,26
1,1371,196,556,112,14,21,11,18,0,12,...,120,103,111,70,90,82,111,70,215,116
2,1140,233,638,166,73,57,0,12,47,44,...,40,42,0,24,24,36,0,24,10,27
3,1655,243,825,140,61,36,11,11,12,18,...,51,36,15,23,20,17,15,23,22,18
4,709,159,378,100,11,17,58,47,7,12,...,4,19,7,23,7,23,7,23,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,1555,274,904,190,0,12,50,44,15,16,...,72,60,133,83,102,64,133,83,122,98
556,606,161,327,106,11,12,50,51,23,23,...,40,26,21,18,36,25,21,18,5,20
557,1458,168,737,101,21,12,28,24,60,21,...,33,21,41,25,29,18,41,25,21,18
558,1802,152,877,94,74,29,47,32,46,26,...,26,22,55,28,50,26,55,28,69,77
559,1014,145,503,98,19,18,32,22,49,31,...,33,31,50,30,52,37,50,30,21,21